const mongoose = require('mongoose');

const trafficDataSchema = new mongoose.Schema({
  // Unique identifier (auto-generated by MongoDB as _id)
  timestamp: {
    type: Date,
    default: Date.now,
    required: true
  },
  city: {
    type: String,
    required: true
  },
  red_light: {
    type: String,
    required: true
  },
  temperature: {
    type: Number,
    required: true
  },
  humidity: {
    type: Number,
    required: true
  },
  speed: {
    type: Number,
    required: true
  },
  no_of_vehicles: {
    type: Number,
    required: true
  }
});

module.exports = mongoose.model('TrafficData', trafficDataSchema);
